### ISSUE TITLE
cannot stat ‘dcmrcv’ in setup-centos7.sh

### ISSUE THREAD

**Issue by naegelejd** [gbook/nidb#10]
I'm using the `setup-centos7.sh` script and it fails to copy `dcmrcv` near the end. Here's a simple patch:

```diff
diff --git a/setup/setup-centos7.sh b/setup/setup-centos7.sh
old mode 100644
new mode 100755
index 2cfa0fc..4b4a8bc
--- a/setup/setup-centos7.sh
+++ b/setup/setup-centos7.sh
@@ -221,7 +221,7 @@ echo "Installing dcm4che receiver to listen on port 8104"
 #read -p "Press [enter] to continue"
 
 # add dcmrcv service at boot
-cp dcmrcv /etc/init.d
+cp ${NIDBROOT}/install/programs/dcmrcv /etc/init.d
 chmod 755 /etc/init.d/dcmrcv
 chkconfig --add dcmrcv
 
```

**Comment by gbook** [comment]
Thanks! I'll change it. I should also mention you may run into other bugs with the setup script as we are still working on migrating to CentOS 7. init is disabled by default in CentOS 7, so the above will not work as scripted. You will need to manually setup the dcmrcv program to start at runtime.

Also, some of the cpan (particularly Net::SMTP::TLS) modules will install correctly in the setup script, but the Perl modules will not run, saying the Perl libraries cannot be found.

We're working on these setup issues, but keep contributing. Thanks!

**Comment by naegelejd** [comment]
Great thanks! I didn't even think about your point regarding init in CentOS
7. I'm still getting used to systemd.

--
Joe Naegele
joseph.naegele@gmail.com
josephnaegele.com
301.676.1403
