### ISSUE TITLE
sub-ID and ses-ID for BIDS exports

### ISSUE THREAD

**Issue by andersonwinkler** [gbook/nidb#123]
When we export as BIDS, we currently have 2 additional options:

- UID instead of sub-0001
- StudyNum instead of ses-0001

How about if this were changed such that we'd have two sets single-choice checkboxes:

Subject ID:
- Use sub-0001
- Use sub-UID
- Use sub-AltID

Session ID:
- Use ses-0001
- Use ses-StudyNum
- Use ses-AltStudyID
- Use ses-YYYYMMDD

It would be so handy... thanks!

**Comment by gbook** [comment]
fixed in next version
