### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Mcstevens** [gbook/nidb#2]
Hi Greg... Two more simple ideas for you to consider whether they’d be useful additions to ADO2.  (In other words, neither are critically needed, just stuff I noticed along the way).  The first is whether or not an email notification system might be a good thing to add back into the mix, e.g., once a script successfully/unsuccessfully finishes, a list of email addresses could be contacted with a standard notification.

Second... A potentially useful flexibility on the Pipeline Specification for Primary Data might be to... instead of having a flag up above (Data download) that specifies “or” “and” or “none”... Perhaps instead have options down in the data specification section that says “Click if MUST” be present vs. another box that says “Click to download IF it’s there” (i.e., but don’t prevent the processing of other data just ‘cause it’s not).  For instance, I can picture the convenience of having a single pipeline that processes the fixed battery of scans that comes from someone’s paradigm.  But what if someone completes all but 1 of those scans?  Right now, you’d have to set up a completely separate pipeline (e.g., HCP) to do the processing... or do it by hand.  But, by increasing the flexibility of the data specificiation, one can not only have the full flexibility of “OR”... But one can specify situations where absolutely required scans (e.g., fieldmaps) MUST be present, but that any and all fMRI data in that study could be run.  Again, not a huge tweak, but maybe worth thinking about?

**Comment by gbook** [comment]
Split into two issues and condensed the enhancement specifications
