### ISSUE TITLE
Data Received but not archived (NiDB Uploader)

### ISSUE THREAD

**Issue by aliaarefi** [gbook/nidb#48]
while trying to upload DICOM data via NiDB uploader, everything goes well, all files get received successfully but can't get archived. I can't find any problem with anything.

**Comment by gbook** [comment]
Is this being uploaded to a server that you installed? I would check permissions to projects, and see if the parsedicom.pl program is running correctly.

Also, look at the Import --> Import Logs web page. It will show all imports (when logged in as admin) and their status.

**Comment by aliaarefi** [comment]
We've been trying to upload DICOM files via NiDB uploader on our already
installed NiDB server but we faced some problems.

The logs show that the imaging files, are uploaded, checked and received
successfully but due to an unknown error, none of the files are archived.
(screenshots attatched)

All of the parts related to creating a new project, new study and new
subject, and permissions have been done successfully but the archiving and
assigning DICOM images to a specific patient were unsuccessfull.

I think that it can be due to an error in Parsdicom.pl, but how can I make
sure about parsdicom.pl working correctly?

I'd appreciate it if you could help me with this.

Best regards.
Ali Aarefi

**Comment by gbook** [comment]
I'm not seeing any screenshots. Can you copy the message or try uploading the screenshots again?

Does the list of projects show up in the NiDBUploader?

**Comment by aliaarefi** [comment]
Yes, the list of projects in NiDB uploader shows up.

The screenshots rar file :

**Comment by gbook** [comment]
Closing this issue, because no response in a few months
