### ISSUE TITLE
Add edit-in-place visit and date on study page

### ISSUE THREAD

**Issue by gbook** [gbook/nidb#58]
For non-MR studies:
1) add edit-in-place to the Study page, for datetime and visit type.
2) add option to change all series datetimes to match the study datetime when editing the study datetime

**Comment by asimmubeen** [comment]
1. Convert datetime and visit type to editable fields on the Study page.
2.  Option to change all series datetime to match the study datetime is available now.
3. Changes are only for Non-MRI studies.
