### ISSUE TITLE
Uninstall procedure for Centos 7?

### ISSUE THREAD

**Issue by dorianps** [gbook/nidb#61]
Hi again,

Is there a procedure or script I can use to uninstall NIDB from a Centos 7 workstation? I.e., including removing the `nidb` user, databases, etc.

Thank you.
Dorian

**Comment by gbook** [comment]
We have not developed an uninstall script for NiDB. But if you follow the procedures in the install script in reverse, you should be able to remove most of the parts.

**Comment by dorianps** [comment]
Just spent an entire afternoon trying to uninstall nidb, and to some degree succeeded. But this installation makes a lot of changes, including security changes such as disabling `firewalld` to install iptables. Some of the changes made by this software affect the whole system and may be irreversible. And at least from a programming perspective, I think it would be useful for users to provide an uninstall script. It is common practice among developers I think.
