### ISSUE TITLE
Field 'series_numfiles' doesn't have a default value

### ISSUE THREAD

**Issue by andersonwinkler** [gbook/nidb#64]
Sometimes we have paper documents that are scanned (not like MRI-scanned, just using a common office scanner), that land in the import area. We don't mind these being imported, but it crashes due to a non-default value:

`[06/16/2019 15:46:10][pid 23987] SQL Error: 'insert into ot_series (study_id, series_datetime, series_desc, series_sequencename, series_num, series_spacingx, series_spacingy, series_spacingz, img_rows, img_cols, img_slices, numfiles, modality, data_type, series_status, series_createdby) values (8166, '2019-06-10 19:03:37', '', '', '0', '0', '0', '0', '3300', '2550', '2', '2', 'OT', 'dicom', 'complete', 'parsedicom')' in statement [[File: parsedicom.pl Line: 1137]Field 'series_numfiles' doesn't have a default value]`

**Comment by gbook** [comment]
That is annoying. This is fixed in the compiled version.
