### ISSUE TITLE
Beginner set up question

### ISSUE THREAD

**Issue by NinjMenon** [gbook/nidb#68]
Hi, 
This may be a super basic question and have a very simple answer: 

My lab is trying to use NiDB to host some of our data and I followed all the instructions on the GitHub README and the Admin doc for installation. 

Everything seemed to have gone through fine, and I edited the /nidb/programs/nidb.cfg.sample to put in the password for the user account that I created (called nidb) and renamed the file to /nidb/programs/nidb.cfg. I also edited all the paths to reflect where nidb is installed (/nidb instead of /home/nidb). I then went to http:/localhost to log in as the admin, but all I see is a blank page. I can see that it recognizes the install - the title is localhost - NiDB, but don't see any web GUI/widget options on the page.

Is there something that I missed during the installation? 

Thanks for your help, 
Niranjana

**Comment by NinjMenon** [comment]
Just wanted to update on this issue: If I don't rename the nidb.cfg.sample file to nidb.cfg, I am able to see the login page, but can't log in with user = admin and password = password, user = root, password = password, or user= = nidb , password = password. If I rename it, the whole page goes blank. Thanks for your help!

**Comment by gbook** [comment]
Curious which version you are using? I've created a new installer, which is not described in the README. It only applies to CentOS/RedHat  8 though.

**Comment by NinjMenon** [comment]
I was using the data from this release: https://github.com/gbook/nidb/releases/tag/2019a. 

Does the new installer also take care of necessary dependencies or do we still need to install them as described in the README/admin doc? Thanks for your help!

**Comment by gbook** [comment]
Try this (beta) release if you can: https://github.com/gbook/nidb/releases/tag/2019.1.44

You will need CentOS 8, and you may need to remove (or rename) the existing /nidb directory if you've previously installed it.

**Comment by NinjMenon** [comment]
Hi @gbook, I tried running the new installer on a CentOS 8 VM and it looked like it finished without issues. However, right after it finished it tried to open http://localhost/setup.php and got a 503 Service Unavailable response. Is there anything I missed during the install that could be causing problems? This is a new environment, so this is a fresh install in a brand new system.

**Comment by NinjMenon** [comment]
Update: I deleted the /nidb folder and reran the installer and got the following error: `Error during installation process (nidb.config):
Execution failed (Unexpected exit code: 1): "mysqladmin -u root password password"` 

This is why the setup page can't load. Any thoughts?

**Comment by gbook** [comment]
You can ignore the mysqladmin error, it's just saying that the root password has already been set.

Looks like the beta installer is still beta :) and has some bugs.

Are you using VirtualBox? It might be easier for me to publish a functioning VirtualBox VM that you can download to test it out yourself.

**Comment by NinjMenon** [comment]
I'm using VMWare. Our systems don't come installed with VirtualBox, but I could use Vagrant to pull up the VirtualBox VM. I think that could work.

**Comment by gbook** [comment]
I'll create a virtual box vm then, and pay a link to it. That may be a good
temporary measure so you can test it out until i fix the installer.

**Comment by NinjMenon** [comment]
Sounds great, thanks!

**Comment by NinjMenon** [comment]
Hi @gbook, just wanted to check in and see if there is an update on this. Thanks!

**Comment by gbook** [comment]
Working on it! Thank you for your patience.

**Comment by gbook** [comment]
The latest installer should probably work. If you want to try the VirtualBox appliance, there is an instance available for download here: http://olinnidb.org/download/CentOS8-NiDB.ova
