### ISSUE TITLE
Prioritize datasets that are farthest along in the pipeline when submitting jobs.

### ISSUE THREAD

**Issue by ronaldjj** [gbook/nidb#69]
Sometimes the results script needs to be rerun, or it needs to be rechecked for success. It would be preferable if these things went to the top of the job queue. Or at the very least come before starting analysis on a new dataset.

**Comment by gbook** [comment]
When the pipeline manager starts, it will now queue studies in the following order:

1. results rerun
2. supplement run
3. all other studies not yet run, that meet criteria for running
