### ISSUE TITLE
Beginner Questions

### ISSUE THREAD

**Issue by tjhendrickson** [gbook/nidb#83]
Hi Gregory,

I have looked through this repository and I am very impressed with NIDB. Very well done! Say I have a few questions about the interface and the accepted file types. I looked through previous issues and a little bit through the documentation and source code before deciding to craft this message. If I missed some information that has already been posted I apologize!

Anyway my questions are:
1) Does NIDB accept BIDS organized data? If it does not support direct ingestion of BIDS organized data is there a way to import JSON which stores key value DICOM header information and place those within the DICOM header fields for each DICOM/NII scan?
2) On NITRC I noticed that nearly all known neuroimaging data formats are accepted! That's fantastic! For my specific use case I would like to upload previously processed data with the HCP pipeline into NIDB. Would NIDB be able to handle something like this? 

Thanks much!

Best,

-Tim

**Comment by gbook** [comment]
Hi Tim,
NiDB is designed to store any type of binary data. Getting the data into the system is a different story though. DICOM, PAR/REC, and EEG, ET all have methods for importation. Processed (analysed) data does not have a method for import. While BIDS export through NiDB sort of works, there is not currently a method to import data using BIDS format. If that's something that it is important to you or the community, we can investigate implementing that. Or if you're familiar with C++ and SQL, you're welcome to contribute code to import BIDS :-)
-G
