### ISSUE TITLE
Current installation instructions?

### ISSUE THREAD

**Issue by trevor** [gbook/nidb#85]
The README references two PDF files that aren't included in the repository:

```
Follow the NiDB-Install.pdf directions included with the current release.

Follow the NiDB-Build.pdf directions included with the current release.
```

Is `doc/NiDB-Administrator-Guide.docx` up-to-date? I see it has a date of 2015.

**Comment by gbook** [comment]
The administrator guide is not up-to-date. Some things may still apply, but a lot of the material is not current, since we've re-written large parts of the backend code.

I updated the current release with the latest Install and Build PDFs, and those are up-to-date.

**Comment by trevor** [comment]
Where can I find those PDFs? It appears the latest commit was 8 days ago.

**Comment by gbook** [comment]
The PDFs are in the current release https://github.com/gbook/nidb/releases

**Comment by trevor** [comment]
Got it, that location wasn't clear from the README. Looks good, thank you!
