### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by andersonwinkler** [gbook/nidb#95]
Hi Greg,

The partition we use for `/nidb/data/archive` has 20TB, of which we are using a little over 10TB. However, we've run out of inodes (100%!), then we can create any new file.

Your instance at ONRC has surely more files. How to deal with this?

Thanks!

Cheers,

Anderson

**Comment by gbook** [comment]
What filesystem are you using? I believe we are using zfs with around 20TB
of raw data.

Also, you may want to attempt an upgrade of your insurance to the current
version of nidb. It went fix the inode issue, but there are lots of bug
fixes and improvements since last summer.

**Comment by andersonwinkler** [comment]
Thanks for the quick response. I think we are using ext4. I'll move the data off, format as zfs, and put them back.

Will upgrade too, many thanks!
